name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Run static checks
      # TODO: replace with `make check` once `make lint` is happy
      run: make gofmt ineffassign staticcheck vet

    - name: Send slack notification
      if: ${{ (cancelled() || failure()) && (github.event_name == 'schedule' || github.event_name == 'push') }}
      uses: 8398a7/action-slack@dcc8c8e9dd8802e21a712dc0c003db97b42efe43
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
